import * as React from "react";
import Box from "@mui/material/Box";
import Drawer from "@mui/material/Drawer";
import Toolbar from "@mui/material/Toolbar";
import { Typography } from "@mui/material";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";


export default function AiAssistant({ open, toggleAiDrawer }) {
  const messages = [
    {
      id: 1,
      primary: "Brunch this week?",
      secondary:
        "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: "/static/images/avatar/5.jpg",
    },
    {
      id: 2,
      primary: "Birthday Gift",
      secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      person: "/static/images/avatar/1.jpg",
    },
    {
      id: 3,
      primary: "Recipe to try",
      secondary:
        "I am try out this new BBQ recipe, I think this might be amazing",
      person: "/static/images/avatar/2.jpg",
    },
    {
      id: 4,
      primary: "Yes!",
      secondary: "I have the tickets to the ReactConf for this year.",
      person: "/static/images/avatar/3.jpg",
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary:
        "My appointment for the doctor was rescheduled for next Saturday.",
      person: "/static/images/avatar/4.jpg",
    },
    {
      id: 6,
      primary: "Discussion",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      person: "/static/images/avatar/5.jpg",
    },
    {
      id: 7,
      primary: "Summer BBQ",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
      person: "/static/images/avatar/1.jpg",
    },
  ];


  return (
    <Drawer anchor="right"  open={open} 
    sx={{
      width: 240, // Set your desired width
      flexShrink: 0,
      '& .MuiDrawer-paper': {
        width: "25%", // Also set the width for the paper element
        boxSizing: 'border-box',
      },
    }}
    onClose={toggleAiDrawer(false)}>
        <Toolbar />
        <Typography
          variant="h5"
          gutterBottom
          component="div"
          sx={{ p: 2, pb: 0 }}
        >
          Personal Productivity Assistant
        </Typography>
        <List sx={{ mb: 2, width: "100%" }}>
          {/*Placeholder Text Logic*/}
          {messages.map(({ id, primary, secondary }) => (
            <React.Fragment key={id}>
              {id === 1 && <ListSubheader>Today</ListSubheader>}
              {id === 3 && <ListSubheader>Yesterday</ListSubheader>}
              <ListItem>
                <ListItemText primary={primary} secondary={secondary} />
              </ListItem>
            </React.Fragment>
          ))}
        </List>
    </Drawer>
  );
}
